- name: Print Hello World
  ansible.builtin.debug:
    msg: "I am from role sample"

- name: print variable from role
  ansible.builtin.debug:
    msg: url-{{URL}}

- name: print variable from play
  ansible.builtin.debug:
    msg:URL_PLAY:{{URL_PLAY}}